main: main.cpp
	g++ -O0 -g -Wall -Wextra -fopenmp -std=c++17 -o main main.cpp -lhiredis -lredis++ -pthread

fill_matrix: fill_matrix.cpp
	g++ -O0 -g -Wall -Wextra -fopenmp -std=c++17 -o fill_matrix fill_matrix.cpp -lhiredis -lredis++ -pthread 